repos:

  - repo: https://github.com/pycqa/isort
    rev: 5.5.4
    hooks:
      - id: isort
        args: [ --multi-line=3, --trailing-comma, --force-grid-wrap=0, --use-parentheses, --line-width=88]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      additional_dependencies: ["flake8-eradicate==0.4.0"]
      args: [--max-line-length=89]


  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 4.0.0  # pick a git hash / tag to point to
    hooks:
    -   id: pydocstyle
        args: [--convention=numpy, --add-ignore=D104]

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.8.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==20.8b1]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: ^docs/*
      - id: end-of-file-fixer
        exclude: ^docs/*
      - id: debug-statements
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: mixed-line-ending
      - id: check-toml
      - id: pretty-format-json
      - id: check-docstring-first
      - id: check-symlinks
      - id: detect-private-key
