site_name: fitburst
site_author: Emmanuel Fonseca
site_description: "Maestro Backend :: URL Prefix"
repo_name: chimefrb/fitburst
repo_url: "https://github.com/chimefrb/fitburst"
copyright: Copyright &copy; 2016 - 2020 CHIME/FRB Collaboration

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  features:
    - tabs

plugins:
  - search

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_code_format"
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - About: about.md
  - Installation: installation.md
  - Usage: 
    - Format of Input Data: usage/formatting_data_generic.md
    - Working with Data Readers: usage/using_data_readers.md
  - Developer Guide: 
    - Coding Philosophy: developer_guide/philosophy.md
    - Package Structure: developer_guide/package_structure.md
    - Writing Data Readers: developer_guide/readers.md
