name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches: [ main ]
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - '**'

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v3
      -
        name: Install Poetry
        run: pipx install poetry
      -
        name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'poetry'
      -
        name: Install Dependencies
        run: poetry install
      -
        name: Run Pre-Commit
        run: poetry run pre-commit run --all-files --show-diff-on-failure

  tests:
    needs: pre-commit-checks
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v3
      -
        name: Install Poetry
        run: pipx install poetry
      -
        name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'poetry'
      -
        name: Install Dependencies
        run: poetry install

      - name: Run Tests
        run: |
          poetry run pytest
