name: Tests

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches: [ main ]
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - '**'

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files

  tests:
    needs: pre-commit-checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - uses: webfactory/ssh-agent@v0.4.1
      with:
          ssh-private-key: ${{ secrets.CHIMEFRB_BOT_SSH_PRIVATE_KEY }}
    - name: Installation
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run Tests
      run: |
        poetry run pytest
